services:
  pdvappdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  pdvapp.api:
    image: ${DOCKER_REGISTRY-}pdvappapi
    build:
      context: .
      dockerfile: PDVApp.Api/Dockerfile

volumes:
  pgadmin_data:
  postgres_data:
